language: python
deploy:
  provider: pypi
  user: cjrk
  password:
    secure: dqR5LrQgQ4xmWOJCpyvaTFXg7Q35yI5gw6yJypA90Pmz+R3pHLhiq2+3uOeYFIDQoe6CzcwPh1Uvu2SQV3PdDhB1ZjbccsWQQ9WOF4kOkt0ZUoyQlDB+VwiO/nEpjFze7n4VZFFtEVSwd1wmkEAmwDxl5iFvOqDzVkFhDjn3Abp+yZL28vofYaDuwFjCCRPY5L6CQUAE73JixeK7kQNRbIvNsRSZauxNEYPNd9ofdiyyiObY1haWsbVRxMMI+bvnuJWcnNromEEqBfsmsf4PrVZeO8kTRmVYmGhHx87b/OGOkjIMadxAm8tmgh2wjkJuGq+th/Gt7A2CD1H90h85RbRVNwxgU/QJh7ehNsLIMJaJ0iXD3qvQXtpz1YWY/O+Q6I8inaWjU58z2dbdNFShq2NflLNn9ls4k4RmIMn78SI0QzhCYC9FFBYLXe92x3mqonD3zYXc09Z1p7kzqXu6mhGwpk77qK+AIJIwnHE98VgD5UMnfBtxAF0qZ3HGGfWm0gonGRHIhKTccAl/bQ3aLtrAYEm29RMK4TXw5DZI6n/ODLMqXH7RBwE89hUoeVyNg1zNxdka7reDrymI4hJYzhTMljEGS5SUWyo3OZmheJlJ6FUIQiULpNhO8NusLXilknzSMGaHNdiVwklw5Vrs7cDHWx1oxokGWIIW7Y6ZJlk=
  on:
    tags: true
    repo: cjrk/AllTheDots
